spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix:
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://119.23.209.49:3306/weijie?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 2
      max-active: 50
      min-idle: 5
      max-wait: 60000 # 60s
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: SELECT 'x' FROM DUAL
      validation-query-timeout: 60 # 60s
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 60000
      max-evictable-idle-time-millis: 60000
      filters: stat,wall
      web-stat-filter:
        enabled: true
        # url-p attern:
        # exclusions:
        # session-stat-enable: true
        # session-stat-max-count:
        # principal-session-name:
        # principal-cookie-name:
        # profile-enable:
      stat-view-servlet:
        enabled: true
        # url-pattern:
        reset-enable: false
        login-username: druid
        login-password: druid
        #allow:
        #deny:


mybatis-plus:
  mapper-locations: classpath:/com/wei/mapper/*Mapper.xml
  typeAliasesPackage: com.wei.pojo
  global-config:
    id-type: 0
    field-strategy: 1
    db-column-underline: true
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
    log-prefix: 'dao.'
#log4j:
#  rootLogger: DEBUG, stdout
logging:
  level:
#    ROOT: debug
    org.springframework.web: DEBUG
    com:
      com:
        wei:
          mapper: debug
 #         service: debug
 #         controller: debug
callback:
  system:
    url: http:localhost


